/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Login
 */
export const LoginBody = zod.object({
  email: zod.email(),
  password: zod.string(),
});

export const loginResponseMin = 0;

export const LoginResponse = zod.number().min(loginResponseMin);

/**
 * @summary Create a user
 */
export const CreateUserBody = zod
  .object({
    email: zod.email(),
    password: zod.string(),
  })
  .and(
    zod.object({
      name: zod.object({
        first: zod.string(),
        last: zod.string(),
      }),
    }),
  );

/**
 * @summary Read a user
 */
export const readUserPathIdMin = 0;

export const ReadUserParams = zod.object({
  id: zod
    .number()
    .min(readUserPathIdMin)
    .describe("The unique identifier of the user"),
});

export const readUserResponseIdMin = 0;

export const ReadUserResponse = zod.object({
  id: zod.number().min(readUserResponseIdMin),
  name: zod.object({
    first: zod.string(),
    last: zod.string(),
  }),
  description: zod.string(),
  admin: zod.boolean().optional(),
});

/**
 * @summary Update a user
 */
export const updateUserPathIdMin = 0;

export const UpdateUserParams = zod.object({
  id: zod
    .number()
    .min(updateUserPathIdMin)
    .describe("The unique identifier of the user"),
});

/**
 * @summary Delete a user
 */
export const deleteUserPathIdMin = 0;

export const DeleteUserParams = zod.object({
  id: zod
    .number()
    .min(deleteUserPathIdMin)
    .describe("The unique identifier of the user"),
});
