/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a reservation
 */
export const createReservationBodyIdMin = 0;

export const createReservationBodyUserIdMin = 0;

export const createReservationBodyLabIdMin = 0;

export const createReservationBodySlotIdsItemMin = 0;



export const CreateReservationBody = zod.object({
  "id": zod.number().min(createReservationBodyIdMin),
  "userId": zod.number().min(createReservationBodyUserIdMin),
  "labId": zod.number().min(createReservationBodyLabIdMin),
  "anonymous": zod.boolean().optional(),
  "schedule": zod.object({
  "start": zod.iso.datetime({}),
  "end": zod.iso.datetime({})
}).describe('Time interval'),
  "slotIds": zod.array(zod.number().min(createReservationBodySlotIdsItemMin))
})

/**
 * @summary Update a reservation
 */
export const updateReservationPathIdMin = 0;



export const UpdateReservationParams = zod.object({
  "id": zod.number().min(updateReservationPathIdMin).describe('The unique identifier of the reservation')
})

/**
 * @summary Delete a reservation
 */
export const deleteReservationPathIdMin = 0;



export const DeleteReservationParams = zod.object({
  "id": zod.number().min(deleteReservationPathIdMin).describe('The unique identifier of the reservation')
})

/**
 * @summary Read the reservations of the user
 */
export const getReservationUserPathIdMin = 0;



export const GetReservationUserParams = zod.object({
  "id": zod.number().min(getReservationUserPathIdMin).describe('The unique identifier of the user')
})

export const getReservationUserResponseIdMin = 0;

export const getReservationUserResponseUserIdMin = 0;

export const getReservationUserResponseLabIdMin = 0;

export const getReservationUserResponseSlotIdsItemMin = 0;



export const GetReservationUserResponseItem = zod.object({
  "id": zod.number().min(getReservationUserResponseIdMin),
  "userId": zod.number().min(getReservationUserResponseUserIdMin),
  "labId": zod.number().min(getReservationUserResponseLabIdMin),
  "anonymous": zod.boolean().optional(),
  "schedule": zod.object({
  "start": zod.iso.datetime({}),
  "end": zod.iso.datetime({})
}).describe('Time interval'),
  "slotIds": zod.array(zod.number().min(getReservationUserResponseSlotIdsItemMin))
})
export const GetReservationUserResponse = zod.array(GetReservationUserResponseItem)

/**
 * @summary Read the reservations of the lab
 */
export const getReservationLabPathIdMin = 0;



export const GetReservationLabParams = zod.object({
  "id": zod.number().min(getReservationLabPathIdMin).describe('The unique identifier of the lab')
})

export const getReservationLabResponseIdMin = 0;

export const getReservationLabResponseUserIdMin = 0;

export const getReservationLabResponseLabIdMin = 0;

export const getReservationLabResponseSlotIdsItemMin = 0;



export const GetReservationLabResponseItem = zod.object({
  "id": zod.number().min(getReservationLabResponseIdMin),
  "userId": zod.number().min(getReservationLabResponseUserIdMin),
  "labId": zod.number().min(getReservationLabResponseLabIdMin),
  "anonymous": zod.boolean().optional(),
  "schedule": zod.object({
  "start": zod.iso.datetime({}),
  "end": zod.iso.datetime({})
}).describe('Time interval'),
  "slotIds": zod.array(zod.number().min(getReservationLabResponseSlotIdsItemMin))
})
export const GetReservationLabResponse = zod.array(GetReservationLabResponseItem)

