/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestResponse,
  ExistsResponse,
  GetReservationLab200Item,
  GetReservationUser200Item,
  Id,
  NotFoundResponse,
  Reservation,
  UnauthorizedResponse,
  UnexpectedResponse,
} from "../../models";

/**
 * @summary Create a reservation
 */
export type createReservationResponse201 = {
  data: Id;
  status: 201;
};

export type createReservationResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type createReservationResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createReservationResponse409 = {
  data: ExistsResponse;
  status: 409;
};

export type createReservationResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type createReservationResponseSuccess = createReservationResponse201 & {
  headers: Headers;
};
export type createReservationResponseError = (
  | createReservationResponse400
  | createReservationResponse401
  | createReservationResponse409
  | createReservationResponse500
) & {
  headers: Headers;
};

export type createReservationResponse =
  | createReservationResponseSuccess
  | createReservationResponseError;

export const getCreateReservationUrl = () => {
  return `/api/reservation`;
};

export const createReservation = async (
  reservation: Reservation,
  options?: RequestInit,
): Promise<createReservationResponse> => {
  const res = await fetch(getCreateReservationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(reservation),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createReservationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createReservationResponse;
};

export const getCreateReservationMutationOptions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | ExistsResponse
    | UnexpectedResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReservation>>,
    TError,
    { data: Reservation },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReservation>>,
  TError,
  { data: Reservation },
  TContext
> => {
  const mutationKey = ["createReservation"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReservation>>,
    { data: Reservation }
  > = (props) => {
    const { data } = props ?? {};

    return createReservation(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createReservation>>
>;
export type CreateReservationMutationBody = Reservation;
export type CreateReservationMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | ExistsResponse
  | UnexpectedResponse;

/**
 * @summary Create a reservation
 */
export const useCreateReservation = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | ExistsResponse
    | UnexpectedResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReservation>>,
      TError,
      { data: Reservation },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createReservation>>,
  TError,
  { data: Reservation },
  TContext
> => {
  return useMutation(getCreateReservationMutationOptions(options), queryClient);
};
/**
 * @summary Update a reservation
 */
export type updateReservationResponse204 = {
  data: void;
  status: 204;
};

export type updateReservationResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateReservationResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateReservationResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateReservationResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type updateReservationResponseSuccess = updateReservationResponse204 & {
  headers: Headers;
};
export type updateReservationResponseError = (
  | updateReservationResponse400
  | updateReservationResponse401
  | updateReservationResponse404
  | updateReservationResponse500
) & {
  headers: Headers;
};

export type updateReservationResponse =
  | updateReservationResponseSuccess
  | updateReservationResponseError;

export const getUpdateReservationUrl = (id: Id) => {
  return `/api/reservation/${id}`;
};

export const updateReservation = async (
  id: Id,
  options?: RequestInit,
): Promise<updateReservationResponse> => {
  const res = await fetch(getUpdateReservationUrl(id), {
    ...options,
    method: "PUT",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateReservationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateReservationResponse;
};

export const getUpdateReservationMutationOptions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | UnexpectedResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateReservation>>,
    TError,
    { id: Id },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateReservation>>,
  TError,
  { id: Id },
  TContext
> => {
  const mutationKey = ["updateReservation"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateReservation>>,
    { id: Id }
  > = (props) => {
    const { id } = props ?? {};

    return updateReservation(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateReservation>>
>;

export type UpdateReservationMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | UnexpectedResponse;

/**
 * @summary Update a reservation
 */
export const useUpdateReservation = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | UnexpectedResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateReservation>>,
      TError,
      { id: Id },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateReservation>>,
  TError,
  { id: Id },
  TContext
> => {
  return useMutation(getUpdateReservationMutationOptions(options), queryClient);
};
/**
 * @summary Delete a reservation
 */
export type deleteReservationResponse204 = {
  data: void;
  status: 204;
};

export type deleteReservationResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type deleteReservationResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteReservationResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteReservationResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type deleteReservationResponseSuccess = deleteReservationResponse204 & {
  headers: Headers;
};
export type deleteReservationResponseError = (
  | deleteReservationResponse400
  | deleteReservationResponse401
  | deleteReservationResponse404
  | deleteReservationResponse500
) & {
  headers: Headers;
};

export type deleteReservationResponse =
  | deleteReservationResponseSuccess
  | deleteReservationResponseError;

export const getDeleteReservationUrl = (id: Id) => {
  return `/api/reservation/${id}`;
};

export const deleteReservation = async (
  id: Id,
  options?: RequestInit,
): Promise<deleteReservationResponse> => {
  const res = await fetch(getDeleteReservationUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteReservationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteReservationResponse;
};

export const getDeleteReservationMutationOptions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | UnexpectedResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteReservation>>,
    TError,
    { id: Id },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteReservation>>,
  TError,
  { id: Id },
  TContext
> => {
  const mutationKey = ["deleteReservation"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteReservation>>,
    { id: Id }
  > = (props) => {
    const { id } = props ?? {};

    return deleteReservation(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteReservation>>
>;

export type DeleteReservationMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | UnexpectedResponse;

/**
 * @summary Delete a reservation
 */
export const useDeleteReservation = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | UnexpectedResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteReservation>>,
      TError,
      { id: Id },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteReservation>>,
  TError,
  { id: Id },
  TContext
> => {
  return useMutation(getDeleteReservationMutationOptions(options), queryClient);
};
/**
 * @summary Read the reservations of the user
 */
export type getReservationUserResponse200 = {
  data: GetReservationUser200Item[];
  status: 200;
};

export type getReservationUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getReservationUserResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getReservationUserResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type getReservationUserResponseSuccess =
  getReservationUserResponse200 & {
    headers: Headers;
  };
export type getReservationUserResponseError = (
  | getReservationUserResponse400
  | getReservationUserResponse404
  | getReservationUserResponse500
) & {
  headers: Headers;
};

export type getReservationUserResponse =
  | getReservationUserResponseSuccess
  | getReservationUserResponseError;

export const getGetReservationUserUrl = (id: number) => {
  return `/api/reservation/user/${id}`;
};

export const getReservationUser = async (
  id: number,
  options?: RequestInit,
): Promise<getReservationUserResponse> => {
  const res = await fetch(getGetReservationUserUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReservationUserResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getReservationUserResponse;
};

export const getGetReservationUserQueryKey = (id: number) => {
  return [`/api/reservation/user/${id}`] as const;
};

export const getGetReservationUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getReservationUser>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationUser>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReservationUserQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReservationUser>>
  > = ({ signal }) => getReservationUser(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReservationUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReservationUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReservationUser>>
>;
export type GetReservationUserQueryError =
  | BadRequestResponse
  | NotFoundResponse
  | UnexpectedResponse;

export function useGetReservationUser<
  TData = Awaited<ReturnType<typeof getReservationUser>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationUser>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReservationUser>>,
          TError,
          Awaited<ReturnType<typeof getReservationUser>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationUser<
  TData = Awaited<ReturnType<typeof getReservationUser>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationUser>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReservationUser>>,
          TError,
          Awaited<ReturnType<typeof getReservationUser>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationUser<
  TData = Awaited<ReturnType<typeof getReservationUser>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationUser>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read the reservations of the user
 */

export function useGetReservationUser<
  TData = Awaited<ReturnType<typeof getReservationUser>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationUser>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReservationUserQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Read the reservations of the lab
 */
export type getReservationLabResponse200 = {
  data: GetReservationLab200Item[];
  status: 200;
};

export type getReservationLabResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getReservationLabResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getReservationLabResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type getReservationLabResponseSuccess = getReservationLabResponse200 & {
  headers: Headers;
};
export type getReservationLabResponseError = (
  | getReservationLabResponse400
  | getReservationLabResponse404
  | getReservationLabResponse500
) & {
  headers: Headers;
};

export type getReservationLabResponse =
  | getReservationLabResponseSuccess
  | getReservationLabResponseError;

export const getGetReservationLabUrl = (id: number) => {
  return `/api/reservation/lab/${id}`;
};

export const getReservationLab = async (
  id: number,
  options?: RequestInit,
): Promise<getReservationLabResponse> => {
  const res = await fetch(getGetReservationLabUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReservationLabResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getReservationLabResponse;
};

export const getGetReservationLabQueryKey = (id: number) => {
  return [`/api/reservation/lab/${id}`] as const;
};

export const getGetReservationLabQueryOptions = <
  TData = Awaited<ReturnType<typeof getReservationLab>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationLab>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReservationLabQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReservationLab>>
  > = ({ signal }) => getReservationLab(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReservationLab>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReservationLabQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReservationLab>>
>;
export type GetReservationLabQueryError =
  | BadRequestResponse
  | NotFoundResponse
  | UnexpectedResponse;

export function useGetReservationLab<
  TData = Awaited<ReturnType<typeof getReservationLab>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationLab>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReservationLab>>,
          TError,
          Awaited<ReturnType<typeof getReservationLab>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationLab<
  TData = Awaited<ReturnType<typeof getReservationLab>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationLab>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReservationLab>>,
          TError,
          Awaited<ReturnType<typeof getReservationLab>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationLab<
  TData = Awaited<ReturnType<typeof getReservationLab>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationLab>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read the reservations of the lab
 */

export function useGetReservationLab<
  TData = Awaited<ReturnType<typeof getReservationLab>>,
  TError = BadRequestResponse | NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReservationLab>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReservationLabQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
