/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Create a reservation
 */
export const createReservationBodyOneSlotIdsItemMin = 0;

export const createReservationBodyTwoUserIdMin = 0;

export const createReservationBodyTwoLabIdMin = 0;

export const CreateReservationBody = zod
  .object({
    anonymous: zod.boolean().optional(),
    schedule: zod
      .object({
        start: zod.iso.datetime({}),
        end: zod.iso.datetime({}),
      })
      .describe("Time interval"),
    slotIds: zod.array(
      zod.number().min(createReservationBodyOneSlotIdsItemMin),
    ),
  })
  .and(
    zod.object({
      userId: zod.number().min(createReservationBodyTwoUserIdMin),
      labId: zod.number().min(createReservationBodyTwoLabIdMin),
    }),
  );

/**
 * @summary Update a reservation
 */
export const updateReservationPathIdMin = 0;

export const UpdateReservationParams = zod.object({
  id: zod.coerce
    .number()
    .min(updateReservationPathIdMin)
    .describe("The unique identifier of the reservation"),
});

export const updateReservationBodySlotIdsItemMin = 0;

export const UpdateReservationBody = zod.object({
  anonymous: zod.boolean().optional(),
  schedule: zod
    .object({
      start: zod.iso.datetime({}),
      end: zod.iso.datetime({}),
    })
    .describe("Time interval"),
  slotIds: zod.array(zod.number().min(updateReservationBodySlotIdsItemMin)),
});

/**
 * @summary Delete a reservation
 */
export const deleteReservationPathIdMin = 0;

export const DeleteReservationParams = zod.object({
  id: zod.coerce
    .number()
    .min(deleteReservationPathIdMin)
    .describe("The unique identifier of the reservation"),
});

/**
 * @summary Read the reservations of the user
 */
export const readReservationUserPathIdMin = 0;

export const ReadReservationUserParams = zod.object({
  id: zod.coerce
    .number()
    .min(readReservationUserPathIdMin)
    .describe("The unique identifier of the user"),
});

export const readReservationUserQueryPageDefault = 1;

export const ReadReservationUserQueryParams = zod.object({
  page: zod.coerce
    .number()
    .min(1)
    .default(readReservationUserQueryPageDefault)
    .describe("Pagination query"),
});

export const readReservationUserResponseOneOneSlotIdsItemMin = 0;

export const readReservationUserResponseOneTwoUserIdMin = 0;

export const readReservationUserResponseOneTwoLabIdMin = 0;

export const readReservationUserResponseTwoIdMin = 0;

export const ReadReservationUserResponseItem = zod
  .object({
    anonymous: zod.boolean().optional(),
    schedule: zod
      .object({
        start: zod.iso.datetime({}),
        end: zod.iso.datetime({}),
      })
      .describe("Time interval"),
    slotIds: zod.array(
      zod.number().min(readReservationUserResponseOneOneSlotIdsItemMin),
    ),
  })
  .and(
    zod.object({
      userId: zod.number().min(readReservationUserResponseOneTwoUserIdMin),
      labId: zod.number().min(readReservationUserResponseOneTwoLabIdMin),
    }),
  )
  .and(
    zod.object({
      id: zod.number().min(readReservationUserResponseTwoIdMin),
      editable: zod.boolean().optional(),
    }),
  );
export const ReadReservationUserResponse = zod.array(
  ReadReservationUserResponseItem,
);

/**
 * @summary Read the reservations of the lab
 */
export const readReservationLabPathIdMin = 0;

export const ReadReservationLabParams = zod.object({
  id: zod.coerce
    .number()
    .min(readReservationLabPathIdMin)
    .describe("The unique identifier of the lab"),
});

export const readReservationLabQueryPageDefault = 1;

export const ReadReservationLabQueryParams = zod.object({
  page: zod.coerce
    .number()
    .min(1)
    .default(readReservationLabQueryPageDefault)
    .describe("Pagination query"),
});

export const readReservationLabResponseOneOneSlotIdsItemMin = 0;

export const readReservationLabResponseOneTwoUserIdMin = 0;

export const readReservationLabResponseOneTwoLabIdMin = 0;

export const readReservationLabResponseTwoIdMin = 0;

export const ReadReservationLabResponseItem = zod
  .object({
    anonymous: zod.boolean().optional(),
    schedule: zod
      .object({
        start: zod.iso.datetime({}),
        end: zod.iso.datetime({}),
      })
      .describe("Time interval"),
    slotIds: zod.array(
      zod.number().min(readReservationLabResponseOneOneSlotIdsItemMin),
    ),
  })
  .and(
    zod.object({
      userId: zod.number().min(readReservationLabResponseOneTwoUserIdMin),
      labId: zod.number().min(readReservationLabResponseOneTwoLabIdMin),
    }),
  )
  .and(
    zod.object({
      id: zod.number().min(readReservationLabResponseTwoIdMin),
      editable: zod.boolean().optional(),
    }),
  );
export const ReadReservationLabResponse = zod.array(
  ReadReservationLabResponseItem,
);
