/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Reservation
} from '../../models';


export const getCreateReservationResponseMock = (overrideResponse: Partial< Reservation > = {}): Reservation => ({id: faker.number.int({min: 0, max: undefined}), userId: faker.number.int({min: 0, max: undefined}), labId: faker.number.int({min: 0, max: undefined}), anonymous: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), schedule: {start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, slotIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: 0, max: undefined}))), ...overrideResponse})

export const getGetReservationUserResponseMock = (): Reservation[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: 0, max: undefined}), userId: faker.number.int({min: 0, max: undefined}), labId: faker.number.int({min: 0, max: undefined}), anonymous: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), schedule: {start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, slotIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: 0, max: undefined})))})))

export const getGetReservationLabResponseMock = (): Reservation[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: 0, max: undefined}), userId: faker.number.int({min: 0, max: undefined}), labId: faker.number.int({min: 0, max: undefined}), anonymous: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), schedule: {start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, slotIds: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: 0, max: undefined})))})))


export const getCreateReservationMockHandler = (overrideResponse?: Reservation | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Reservation> | Reservation), options?: RequestHandlerOptions) => {
  return http.post('*/reservation', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateReservationResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateReservationMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/reservation/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getDeleteReservationMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/reservation/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getGetReservationUserMockHandler = (overrideResponse?: Reservation[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Reservation[]> | Reservation[]), options?: RequestHandlerOptions) => {
  return http.get('*/reservation/user/:id', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReservationUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetReservationLabMockHandler = (overrideResponse?: Reservation[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Reservation[]> | Reservation[]), options?: RequestHandlerOptions) => {
  return http.get('*/reservation/lab/:id', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReservationLabResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getReservationMock = () => [
  getCreateReservationMockHandler(),
  getUpdateReservationMockHandler(),
  getDeleteReservationMockHandler(),
  getGetReservationUserMockHandler(),
  getGetReservationLabMockHandler()
]
