/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Create a reservation
 */
export const createReservationBodyOneSlotIdsItemMin = 0;

export const createReservationBodyTwoIdMin = 0;

export const createReservationBodyTwoUserIdMin = 0;

export const createReservationBodyTwoLabIdMin = 0;

export const CreateReservationBody = zod
  .object({
    anonymous: zod.boolean().optional(),
    schedule: zod
      .object({
        start: zod.iso.datetime({}),
        end: zod.iso.datetime({}),
      })
      .optional()
      .describe("Time interval"),
    slotIds: zod
      .array(zod.number().min(createReservationBodyOneSlotIdsItemMin))
      .optional(),
  })
  .and(
    zod.object({
      id: zod.number().min(createReservationBodyTwoIdMin),
      userId: zod.number().min(createReservationBodyTwoUserIdMin),
      labId: zod.number().min(createReservationBodyTwoLabIdMin),
    }),
  );

/**
 * @summary Update a reservation
 */
export const updateReservationPathIdMin = 0;

export const UpdateReservationParams = zod.object({
  id: zod
    .number()
    .min(updateReservationPathIdMin)
    .describe("The unique identifier of the reservation"),
});

/**
 * @summary Delete a reservation
 */
export const deleteReservationPathIdMin = 0;

export const DeleteReservationParams = zod.object({
  id: zod
    .number()
    .min(deleteReservationPathIdMin)
    .describe("The unique identifier of the reservation"),
});

/**
 * @summary Read the reservations of the user
 */
export const getReservationUserPathIdMin = 0;

export const GetReservationUserParams = zod.object({
  id: zod
    .number()
    .min(getReservationUserPathIdMin)
    .describe("The unique identifier of the user"),
});

export const getReservationUserResponseOneOneSlotIdsItemMin = 0;

export const getReservationUserResponseOneTwoIdMin = 0;

export const getReservationUserResponseOneTwoUserIdMin = 0;

export const getReservationUserResponseOneTwoLabIdMin = 0;

export const GetReservationUserResponseItem = zod
  .object({
    anonymous: zod.boolean().optional(),
    schedule: zod
      .object({
        start: zod.iso.datetime({}),
        end: zod.iso.datetime({}),
      })
      .optional()
      .describe("Time interval"),
    slotIds: zod
      .array(zod.number().min(getReservationUserResponseOneOneSlotIdsItemMin))
      .optional(),
  })
  .and(
    zod.object({
      id: zod.number().min(getReservationUserResponseOneTwoIdMin),
      userId: zod.number().min(getReservationUserResponseOneTwoUserIdMin),
      labId: zod.number().min(getReservationUserResponseOneTwoLabIdMin),
    }),
  )
  .and(
    zod.object({
      editable: zod.boolean().optional(),
    }),
  );
export const GetReservationUserResponse = zod.array(
  GetReservationUserResponseItem,
);

/**
 * @summary Read the reservations of the lab
 */
export const getReservationLabPathIdMin = 0;

export const GetReservationLabParams = zod.object({
  id: zod
    .number()
    .min(getReservationLabPathIdMin)
    .describe("The unique identifier of the lab"),
});

export const getReservationLabResponseOneOneSlotIdsItemMin = 0;

export const getReservationLabResponseOneTwoIdMin = 0;

export const getReservationLabResponseOneTwoUserIdMin = 0;

export const getReservationLabResponseOneTwoLabIdMin = 0;

export const GetReservationLabResponseItem = zod
  .object({
    anonymous: zod.boolean().optional(),
    schedule: zod
      .object({
        start: zod.iso.datetime({}),
        end: zod.iso.datetime({}),
      })
      .optional()
      .describe("Time interval"),
    slotIds: zod
      .array(zod.number().min(getReservationLabResponseOneOneSlotIdsItemMin))
      .optional(),
  })
  .and(
    zod.object({
      id: zod.number().min(getReservationLabResponseOneTwoIdMin),
      userId: zod.number().min(getReservationLabResponseOneTwoUserIdMin),
      labId: zod.number().min(getReservationLabResponseOneTwoLabIdMin),
    }),
  )
  .and(
    zod.object({
      editable: zod.boolean().optional(),
    }),
  );
export const GetReservationLabResponse = zod.array(
  GetReservationLabResponseItem,
);
