/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Read all labs
 */
export const readLabsQueryPageDefault = 1;

export const ReadLabsQueryParams = zod.object({
  q: zod.coerce.string().optional().describe("The search query to filter labs"),
  page: zod.coerce
    .number()
    .min(1)
    .default(readLabsQueryPageDefault)
    .describe("Pagination query"),
});

export const readLabsResponseOneSlotsItemIdMin = 0;

export const readLabsResponseOneSlotsItemXMin = 0;

export const readLabsResponseOneSlotsItemYMin = 0;

export const readLabsResponseTwoIdMin = 0;

export const ReadLabsResponseItem = zod
  .object({
    name: zod.string(),
    weeklySchedule: zod
      .object({
        sunday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        monday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        tuesday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        wednesday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        thursday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        friday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        saturday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
      })
      .describe("Weekly schedule of the lab"),
    slots: zod
      .array(
        zod.object({
          id: zod.number().min(readLabsResponseOneSlotsItemIdMin),
          x: zod.number().min(readLabsResponseOneSlotsItemXMin),
          y: zod.number().min(readLabsResponseOneSlotsItemYMin),
        }),
      )
      .describe("Available slots in the lab"),
  })
  .and(
    zod.object({
      id: zod.number().min(readLabsResponseTwoIdMin),
      editable: zod.boolean().optional(),
    }),
  );
export const ReadLabsResponse = zod.array(ReadLabsResponseItem);

/**
 * @summary Create a lab
 */
export const createLabBodySlotsItemIdMin = 0;

export const createLabBodySlotsItemXMin = 0;

export const createLabBodySlotsItemYMin = 0;

export const CreateLabBody = zod.object({
  name: zod.string(),
  weeklySchedule: zod
    .object({
      sunday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      monday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      tuesday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      wednesday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      thursday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      friday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      saturday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
    })
    .describe("Weekly schedule of the lab"),
  slots: zod
    .array(
      zod.object({
        id: zod.number().min(createLabBodySlotsItemIdMin),
        x: zod.number().min(createLabBodySlotsItemXMin),
        y: zod.number().min(createLabBodySlotsItemYMin),
      }),
    )
    .describe("Available slots in the lab"),
});

/**
 * @summary Read a lab
 */
export const readLabPathIdMin = 0;

export const ReadLabParams = zod.object({
  id: zod.coerce
    .number()
    .min(readLabPathIdMin)
    .describe("The unique identifier of the lab"),
});

export const readLabResponseOneSlotsItemIdMin = 0;

export const readLabResponseOneSlotsItemXMin = 0;

export const readLabResponseOneSlotsItemYMin = 0;

export const readLabResponseTwoIdMin = 0;

export const ReadLabResponse = zod
  .object({
    name: zod.string(),
    weeklySchedule: zod
      .object({
        sunday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        monday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        tuesday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        wednesday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        thursday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        friday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
        saturday: zod
          .object({
            start: zod.iso.datetime({}),
            end: zod.iso.datetime({}),
          })
          .optional()
          .describe("Time interval"),
      })
      .describe("Weekly schedule of the lab"),
    slots: zod
      .array(
        zod.object({
          id: zod.number().min(readLabResponseOneSlotsItemIdMin),
          x: zod.number().min(readLabResponseOneSlotsItemXMin),
          y: zod.number().min(readLabResponseOneSlotsItemYMin),
        }),
      )
      .describe("Available slots in the lab"),
  })
  .and(
    zod.object({
      id: zod.number().min(readLabResponseTwoIdMin),
      editable: zod.boolean().optional(),
    }),
  );

/**
 * @summary Update a lab
 */
export const updateLabPathIdMin = 0;

export const UpdateLabParams = zod.object({
  id: zod.coerce
    .number()
    .min(updateLabPathIdMin)
    .describe("The unique identifier of the lab"),
});

export const updateLabBodySlotsItemIdMin = 0;

export const updateLabBodySlotsItemXMin = 0;

export const updateLabBodySlotsItemYMin = 0;

export const UpdateLabBody = zod.object({
  name: zod.string(),
  weeklySchedule: zod
    .object({
      sunday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      monday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      tuesday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      wednesday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      thursday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      friday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
      saturday: zod
        .object({
          start: zod.iso.datetime({}),
          end: zod.iso.datetime({}),
        })
        .optional()
        .describe("Time interval"),
    })
    .describe("Weekly schedule of the lab"),
  slots: zod
    .array(
      zod.object({
        id: zod.number().min(updateLabBodySlotsItemIdMin),
        x: zod.number().min(updateLabBodySlotsItemXMin),
        y: zod.number().min(updateLabBodySlotsItemYMin),
      }),
    )
    .describe("Available slots in the lab"),
});

/**
 * @summary Delete a lab
 */
export const deleteLabPathIdMin = 0;

export const DeleteLabParams = zod.object({
  id: zod.coerce
    .number()
    .min(deleteLabPathIdMin)
    .describe("The unique identifier of the lab"),
});
