/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ExistsResponse,
  GetLabsParams,
  Lab,
  NotFoundResponse,
  UnauthorizedResponse,
  UnexpectedResponse,
} from "../../models";

/**
 * @summary Read all labs
 */
export type getLabsResponse200 = {
  data: Lab[];
  status: 200;
};

export type getLabsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getLabsResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type getLabsResponseSuccess = getLabsResponse200 & {
  headers: Headers;
};
export type getLabsResponseError = (getLabsResponse404 | getLabsResponse500) & {
  headers: Headers;
};

export type getLabsResponse = getLabsResponseSuccess | getLabsResponseError;

export const getGetLabsUrl = (params?: GetLabsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/lab?${stringifiedParams}`
    : `/api/lab`;
};

export const getLabs = async (
  params?: GetLabsParams,
  options?: RequestInit,
): Promise<getLabsResponse> => {
  const res = await fetch(getGetLabsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLabsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getLabsResponse;
};

export const getGetLabsQueryKey = (params?: GetLabsParams) => {
  return [`/api/lab`, ...(params ? [params] : [])] as const;
};

export const getGetLabsQueryOptions = <
  TData = Awaited<ReturnType<typeof getLabs>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  params?: GetLabsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLabs>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLabsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLabs>>> = ({
    signal,
  }) => getLabs(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLabs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLabsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLabs>>
>;
export type GetLabsQueryError = NotFoundResponse | UnexpectedResponse;

export function useGetLabs<
  TData = Awaited<ReturnType<typeof getLabs>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  params: undefined | GetLabsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLabs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabs>>,
          TError,
          Awaited<ReturnType<typeof getLabs>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLabs<
  TData = Awaited<ReturnType<typeof getLabs>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  params?: GetLabsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLabs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabs>>,
          TError,
          Awaited<ReturnType<typeof getLabs>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLabs<
  TData = Awaited<ReturnType<typeof getLabs>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  params?: GetLabsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLabs>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read all labs
 */

export function useGetLabs<
  TData = Awaited<ReturnType<typeof getLabs>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  params?: GetLabsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLabs>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLabsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a lab
 */
export type createLabResponse201 = {
  data: Lab;
  status: 201;
};

export type createLabResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createLabResponse409 = {
  data: ExistsResponse;
  status: 409;
};

export type createLabResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type createLabResponseSuccess = createLabResponse201 & {
  headers: Headers;
};
export type createLabResponseError = (
  | createLabResponse401
  | createLabResponse409
  | createLabResponse500
) & {
  headers: Headers;
};

export type createLabResponse =
  | createLabResponseSuccess
  | createLabResponseError;

export const getCreateLabUrl = () => {
  return `/api/lab`;
};

export const createLab = async (
  lab: Lab,
  options?: RequestInit,
): Promise<createLabResponse> => {
  const res = await fetch(getCreateLabUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(lab),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLabResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createLabResponse;
};

export const getCreateLabMutationOptions = <
  TError = UnauthorizedResponse | ExistsResponse | UnexpectedResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLab>>,
    TError,
    { data: Lab },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLab>>,
  TError,
  { data: Lab },
  TContext
> => {
  const mutationKey = ["createLab"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLab>>,
    { data: Lab }
  > = (props) => {
    const { data } = props ?? {};

    return createLab(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLabMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLab>>
>;
export type CreateLabMutationBody = Lab;
export type CreateLabMutationError =
  | UnauthorizedResponse
  | ExistsResponse
  | UnexpectedResponse;

/**
 * @summary Create a lab
 */
export const useCreateLab = <
  TError = UnauthorizedResponse | ExistsResponse | UnexpectedResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLab>>,
      TError,
      { data: Lab },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLab>>,
  TError,
  { data: Lab },
  TContext
> => {
  return useMutation(getCreateLabMutationOptions(options), queryClient);
};
/**
 * @summary Read a lab
 */
export type getLabResponse200 = {
  data: Lab;
  status: 200;
};

export type getLabResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getLabResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type getLabResponseSuccess = getLabResponse200 & {
  headers: Headers;
};
export type getLabResponseError = (getLabResponse404 | getLabResponse500) & {
  headers: Headers;
};

export type getLabResponse = getLabResponseSuccess | getLabResponseError;

export const getGetLabUrl = (id: number) => {
  return `/api/lab/${id}`;
};

export const getLab = async (
  id: number,
  options?: RequestInit,
): Promise<getLabResponse> => {
  const res = await fetch(getGetLabUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLabResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getLabResponse;
};

export const getGetLabQueryKey = (id: number) => {
  return [`/api/lab/${id}`] as const;
};

export const getGetLabQueryOptions = <
  TData = Awaited<ReturnType<typeof getLab>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLab>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLabQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLab>>> = ({
    signal,
  }) => getLab(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getLab>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetLabQueryResult = NonNullable<Awaited<ReturnType<typeof getLab>>>;
export type GetLabQueryError = NotFoundResponse | UnexpectedResponse;

export function useGetLab<
  TData = Awaited<ReturnType<typeof getLab>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLab>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLab>>,
          TError,
          Awaited<ReturnType<typeof getLab>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLab<
  TData = Awaited<ReturnType<typeof getLab>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLab>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLab>>,
          TError,
          Awaited<ReturnType<typeof getLab>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLab<
  TData = Awaited<ReturnType<typeof getLab>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLab>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read a lab
 */

export function useGetLab<
  TData = Awaited<ReturnType<typeof getLab>>,
  TError = NotFoundResponse | UnexpectedResponse,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLab>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLabQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a lab
 */
export type updateLabResponse204 = {
  data: void;
  status: 204;
};

export type updateLabResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateLabResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateLabResponse409 = {
  data: ExistsResponse;
  status: 409;
};

export type updateLabResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type updateLabResponseSuccess = updateLabResponse204 & {
  headers: Headers;
};
export type updateLabResponseError = (
  | updateLabResponse401
  | updateLabResponse404
  | updateLabResponse409
  | updateLabResponse500
) & {
  headers: Headers;
};

export type updateLabResponse =
  | updateLabResponseSuccess
  | updateLabResponseError;

export const getUpdateLabUrl = (id: number) => {
  return `/api/lab/${id}`;
};

export const updateLab = async (
  id: number,
  options?: RequestInit,
): Promise<updateLabResponse> => {
  const res = await fetch(getUpdateLabUrl(id), {
    ...options,
    method: "PUT",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateLabResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateLabResponse;
};

export const getUpdateLabMutationOptions = <
  TError =
    | UnauthorizedResponse
    | NotFoundResponse
    | ExistsResponse
    | UnexpectedResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLab>>,
    TError,
    { id: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLab>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["updateLab"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLab>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return updateLab(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLabMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLab>>
>;

export type UpdateLabMutationError =
  | UnauthorizedResponse
  | NotFoundResponse
  | ExistsResponse
  | UnexpectedResponse;

/**
 * @summary Update a lab
 */
export const useUpdateLab = <
  TError =
    | UnauthorizedResponse
    | NotFoundResponse
    | ExistsResponse
    | UnexpectedResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateLab>>,
      TError,
      { id: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateLab>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getUpdateLabMutationOptions(options), queryClient);
};
/**
 * @summary Delete a lab
 */
export type deleteLabResponse204 = {
  data: void;
  status: 204;
};

export type deleteLabResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteLabResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteLabResponse500 = {
  data: UnexpectedResponse;
  status: 500;
};

export type deleteLabResponseSuccess = deleteLabResponse204 & {
  headers: Headers;
};
export type deleteLabResponseError = (
  | deleteLabResponse401
  | deleteLabResponse404
  | deleteLabResponse500
) & {
  headers: Headers;
};

export type deleteLabResponse =
  | deleteLabResponseSuccess
  | deleteLabResponseError;

export const getDeleteLabUrl = (id: number) => {
  return `/api/lab/${id}`;
};

export const deleteLab = async (
  id: number,
  options?: RequestInit,
): Promise<deleteLabResponse> => {
  const res = await fetch(getDeleteLabUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteLabResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteLabResponse;
};

export const getDeleteLabMutationOptions = <
  TError = UnauthorizedResponse | NotFoundResponse | UnexpectedResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLab>>,
    TError,
    { id: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLab>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteLab"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLab>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteLab(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLabMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLab>>
>;

export type DeleteLabMutationError =
  | UnauthorizedResponse
  | NotFoundResponse
  | UnexpectedResponse;

/**
 * @summary Delete a lab
 */
export const useDeleteLab = <
  TError = UnauthorizedResponse | NotFoundResponse | UnexpectedResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLab>>,
      TError,
      { id: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLab>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteLabMutationOptions(options), queryClient);
};
