/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Lab
} from '../../models';


export const getGetLabsResponseMock = (): Lab[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: 0, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), weeklySchedule: {sunday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), monday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), tuesday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), wednesday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), thursday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), friday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), saturday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined])}, slots: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: 0, max: undefined}), x: faker.number.int({min: 0, max: undefined}), y: faker.number.int({min: 0, max: undefined})}))})))

export const getCreateLabResponseMock = (overrideResponse: Partial< Lab > = {}): Lab => ({id: faker.number.int({min: 0, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), weeklySchedule: {sunday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), monday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), tuesday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), wednesday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), thursday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), friday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), saturday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined])}, slots: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: 0, max: undefined}), x: faker.number.int({min: 0, max: undefined}), y: faker.number.int({min: 0, max: undefined})})), ...overrideResponse})

export const getGetLabResponseMock = (overrideResponse: Partial< Lab > = {}): Lab => ({id: faker.number.int({min: 0, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), weeklySchedule: {sunday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), monday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), tuesday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), wednesday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), thursday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), friday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined]), saturday: faker.helpers.arrayElement([{start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'}, undefined])}, slots: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: 0, max: undefined}), x: faker.number.int({min: 0, max: undefined}), y: faker.number.int({min: 0, max: undefined})})), ...overrideResponse})


export const getGetLabsMockHandler = (overrideResponse?: Lab[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Lab[]> | Lab[]), options?: RequestHandlerOptions) => {
  return http.get('*/lab', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLabsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateLabMockHandler = (overrideResponse?: Lab | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Lab> | Lab), options?: RequestHandlerOptions) => {
  return http.post('*/lab', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateLabResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetLabMockHandler = (overrideResponse?: Lab | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Lab> | Lab), options?: RequestHandlerOptions) => {
  return http.get('*/lab/:id', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLabResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateLabMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/lab/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getDeleteLabMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/lab/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}
export const getLabMock = () => [
  getGetLabsMockHandler(),
  getCreateLabMockHandler(),
  getGetLabMockHandler(),
  getUpdateLabMockHandler(),
  getDeleteLabMockHandler()
]
