/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  User
} from '../../models/index.zod';


export const getLoginResponseMock = (): User => ({...{email: faker.internet.email(), password: faker.internet.password()},...{id: faker.number.int({min: undefined, max: undefined}), name: {first: faker.string.alpha({length: {min: 10, max: 20}}), last: faker.string.alpha({length: {min: 10, max: 20}})}},})

export const getRegisterResponseMock = (): User => ({...{email: faker.internet.email(), password: faker.internet.password()},...{id: faker.number.int({min: undefined, max: undefined}), name: {first: faker.string.alpha({length: {min: 10, max: 20}}), last: faker.string.alpha({length: {min: 10, max: 20}})}},})


export const getLoginMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/login', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getRegisterMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.post('*/login', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRegisterResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getDefaultMock = () => [
  getLoginMockHandler(),
  getRegisterMockHandler()
]
