/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { UserLogin } from "./userLogin";
import type { UserName } from "./userName";

export type CreateUserBody = UserLogin & {
  name: UserName;
};
