/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */

/**
 * ObjectID
 * @pattern ^[0-9a-fA-F]{24}$
 */
export type Id = string;
