/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */

export * from "./badRequestResponse";
export * from "./createUserBody";
export * from "./editable";
export * from "./error";
export * from "./existsResponse";
export * from "./hasNextPage";
export * from "./id";
export * from "./interval";
export * from "./lab";
export * from "./labDetails";
export * from "./labDetailsSlotsItem";
export * from "./labDetailsWeeklySchedule";
export * from "./labId";
export * from "./notFoundResponse";
export * from "./readLabs200";
export * from "./readLabsParams";
export * from "./readUser200";
export * from "./reservationDetails";
export * from "./reservationId";
export * from "./reservationList";
export * from "./reservationListItem";
export * from "./reservationUpdate";
export * from "./unauthorizedResponse";
export * from "./unexpectedResponse";
export * from "./updateUserBody";
export * from "./userDetails";
export * from "./userId";
export * from "./userLogin";
export * from "./userName";
export * from "./userPassword";
