/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */

/**
 * Time interval
 */
export interface Interval {
  start: string;
  end: string;
}
