/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { Id } from './id';
import type { LabSlotsItem } from './labSlotsItem';
import type { LabWeeklySchedule } from './labWeeklySchedule';

export interface Lab {
  id: Id;
  name: string;
  /** Weekly schedule of the lab */
  weeklySchedule: LabWeeklySchedule;
  /** Available slots in the lab */
  slots: LabSlotsItem[];
}
