/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { LabDetailsSlotsItem } from "./labDetailsSlotsItem";
import type { LabDetailsWeeklySchedule } from "./labDetailsWeeklySchedule";

export interface LabDetails {
  name: string;
  /** Weekly schedule of the lab */
  weeklySchedule: LabDetailsWeeklySchedule;
  /** Available slots in the lab */
  slots: LabDetailsSlotsItem[];
}
