/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { SlotId } from './slotId';

export type LabDetailsSlotsItem = {
  id: SlotId;
  /** @minimum 0 */
  x: number;
  /** @minimum 0 */
  y: number;
};
