/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { Interval } from './interval';

/**
 * Weekly schedule of the lab
 */
export type LabDetailsWeeklySchedule = {
  sunday?: Interval;
  monday?: Interval;
  tuesday?: Interval;
  wednesday?: Interval;
  thursday?: Interval;
  friday?: Interval;
  saturday?: Interval;
};
