/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { Id } from './id';

export type LabSlotsItem = {
  id: Id;
  /** @minimum 0 */
  x: number;
  /** @minimum 0 */
  y: number;
};
