/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { LabUpdateSlotsItem } from "./labUpdateSlotsItem";
import type { LabUpdateWeeklySchedule } from "./labUpdateWeeklySchedule";

export interface LabUpdate {
  name?: string;
  /** Weekly schedule of the lab */
  weeklySchedule?: LabUpdateWeeklySchedule;
  /** Available slots in the lab */
  slots?: LabUpdateSlotsItem[];
}
