/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const LoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string()
})

export type LoginBody = zod.infer<typeof LoginBody>;
