/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const Login = zod.object({
  "email": zod.string().email(),
  "password": zod.string()
})

export type Login = zod.infer<typeof Login>;
