/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { Error } from "./error";

/**
 * No items found
 */
export type NotFoundResponse = Error;
