/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { PageParameter } from "./pageParameter";

export type ReadLabsParams = {
  /**
   * The search query to filter labs
   */
  q?: string;
  /**
   * Pagination query
   * @minimum 1
   */
  page?: PageParameter;
};
