/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { Editable } from './editable';
import type { Id } from './id';
import type { UserDetails } from './userDetails';

export type ReadUser200 = UserDetails & {
  id: Id;
  admin?: boolean;
  editable?: Editable;
};
