/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { HasNextPage } from './hasNextPage';
import type { Lab } from './lab';

export type ReadLabs200 = {
  data: Lab[];
  hasNextPage?: HasNextPage;
};
