/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { UserDetails } from './userDetails';
import type { UserPassword } from './userPassword';

export type UpdateUserBody = UserDetails & {
  password?: UserPassword;
};
