/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const User = zod.object({
  "email": zod.string().email(),
  "password": zod.string()
}).and(zod.object({
  "id": zod.number(),
  "name": zod.object({
  "first": zod.string(),
  "last": zod.string()
})
}))

export type User = zod.infer<typeof User>;
