/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * ArchersLab API
 * CCAPDEV MCO
 * OpenAPI spec version: 0.1.0
 */
import type { Id } from './id';
import type { UserName } from './userName';

export type User = UserName & {
  id: Id;
  description: string;
  admin?: boolean;
};
